version: "3"

services:

  we-gateway:
    build:
      dockerfile: dockerfile # Archivo de creacion
      context: .
    ports:
      - "8080:8080" # Puerto para acceso de control WEB
      - "50000:50000"
    container_name: jenkings_container # Nombre del Contenedor
    hostname: jenkings_container
    image: jenkins/blueocean_ci  # Imagen a utilizar, definida y nombrada por dockerfile
    networks:
      j_network:
        ipv4_address: 121.32.0.21

networks:
  j_network:
    driver: bridge
    ipam:
      config:
        - subnet: 121.32.0.0/24